# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CsvToPointsPlugin
                                 A QGIS plugin
 Drag & drop a CSV to create point layer; auto-detect encoding/CRS; optional geocoding.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-19
        copyright            : (C) 2025 by TechTeam Solutions LLC
        email                : info@techteam.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CsvToPointsPlugin class from file CsvToPointsPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .csv_to_points import CsvToPointsPlugin
    return CsvToPointsPlugin(iface)
